name: Gradle Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurer le JDK (ici Java 11 avec Temurin, modifiez si nécessaire)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      # Exécuter la commande de build Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Créer une release sur GitHub uniquement si le commit contient [release]
      - name: Create GitHub Release
        if: contains(github.event.head_commit.message, '[release]')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      # Télécharger l'artefact jar (situé dans ./app/build/libs/SuperWatch*.jar) dans la release
      - name: Upload Release Asset
        if: contains(github.event.head_commit.message, '[release]')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app/build/libs/SuperWatch*.jar
          asset_name: SuperWatch.jar
          asset_content_type: application/java-archive
