name: Build and Release Plugin

on:
  push:
    branches:
      - main  # Change si ton repo utilise un autre nom de branche principale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to Gradlew
        run: chmod +x gradlew

      - name: Debug Check repository structure
        run: ls -R || echo "No files found"

      - name: Debug Check Gradle wrapper
        run: ls -l gradlew || echo "No gradlew file found"

      - name: Verify Gradlew works
        run: ./gradlew --version

      - name: Build with Gradle
        run: ./gradlew build --stacktrace --info

      - name: Check for JAR files
        run: find . -name "*.jar" || echo "No JAR found"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: SuperWatch
          path: ./app/build/libs/SuperWatch*.jar
          if-no-files-found: error
          retention-days: 7

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, '[release]')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: SuperWatch  # Récupère SuperWatch.zip
          path: .

      - name: Get current date
        id: date
        run: echo "tag_name=$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.tag_name }}
          name: Release ${{ env.tag_name }}
          body: "Nouvelle release générée automatiquement."
          draft: false
          prerelease: false
          files: SuperWatch.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
